name: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-1B
inner_params:
- model.layers.0.mlp.gate_proj.weight
- model.layers.0.mlp.up_proj.weight
- model.layers.0.mlp.down_proj.weight
- model.layers.1.mlp.gate_proj.weight
- model.layers.1.mlp.up_proj.weight
- model.layers.1.mlp.down_proj.weight
- model.layers.2.mlp.gate_proj.weight
- model.layers.2.mlp.up_proj.weight
- model.layers.2.mlp.down_proj.weight