name: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-1B
inner_params:
- model.layers.3.mlp.gate_proj.weight
- model.layers.3.mlp.up_proj.weight
- model.layers.3.mlp.down_proj.weight
- model.layers.4.mlp.gate_proj.weight
- model.layers.4.mlp.up_proj.weight
- model.layers.4.mlp.down_proj.weight
- model.layers.5.mlp.gate_proj.weight
- model.layers.5.mlp.up_proj.weight
- model.layers.5.mlp.down_proj.weight