name: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft-template-format-curated-v1-lr2e-6-sample-10
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-1B
inner_params: