name: ${oc.env:SHARE_RES_DIR}/models/qwen/Qwen2.5-1.5B
class_name: Qwen2ForCausalLM
tokenizer_class: Qwen2Tokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/qwen/Qwen2.5-1.5B
inner_params:
- model.layers.13.mlp.gate_proj.weight
- model.layers.13.mlp.up_proj.weight
- model.layers.13.mlp.down_proj.weight
- model.layers.14.mlp.gate_proj.weight
- model.layers.14.mlp.up_proj.weight
- model.layers.14.mlp.down_proj.weight
- model.layers.15.mlp.gate_proj.weight
- model.layers.15.mlp.up_proj.weight
- model.layers.15.mlp.down_proj.weight